NUMPY learning 


In [103]:
import numpy as np 
import sys 

The Basics 

#Applications of numpy
mathematics (matlab replacement)
plotting (matplotlib)
backend (pandas) 
machine learning . .. . . .

In [104]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [105]:
b = np.array([[2.0,3.0,6] , [4.5,7.9,8]])
print (b)

[[2.  3.  6. ]
 [4.5 7.9 8. ]]


In [106]:
#GET DIM 
a.ndim
print(a.ndim)
b.ndim

1


2

In [107]:
#get shape
b.shape

(2, 3)

In [108]:
#get type
a.dtype

dtype('int16')

In [109]:
#get size
a.itemsize

2

In [110]:
#get len and no bytes
a.size
a.nbytes # len * size

6

Accessing / changing specific elements, rows, columns, etc

In [111]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)
a.shape

#get specific element
a[1,4] #negative notation too 

#specific row 
a[0,:]

#specific col
a[:,3]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([ 4, 11])

In [112]:
#start ind to end ind and stepsize
a[0,1:6:2] #end ind exclusive

array([2, 4, 6])

In [113]:
a[1, 5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [114]:
#3d example
b = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [115]:
#work outside in for specific element
b[0,:,1]

array([2, 4])

In [116]:
b[:,1,:] = [[69,69],[69,69]]
print(b)

[[[ 1  2]
  [69 69]]

 [[ 5  6]
  [69 69]]]


Initializing diff types of arrays

In [117]:
#all 0s matrix
np.zeros((2,3), dtype='int32') #ones also similar

#any other number
np.full((2,2),99,dtype='float32')


array([[99., 99.],
       [99., 99.]], dtype=float32)

In [118]:
#any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [119]:
#random decim numbers
np.random.randint((4,2))
np.random.rand(4,2)

array([[0.9638464 , 0.80554356],
       [0.50716083, 0.99755683],
       [0.31106873, 0.41724967],
       [0.05688187, 0.38612967]])

In [120]:
#with some shape 
np.random.random_sample(a.shape)

array([[0.58786083, 0.77971702, 0.62043625, 0.11118283, 0.47326271,
        0.51750105, 0.52533695],
       [0.86508624, 0.50303225, 0.63422883, 0.05863572, 0.40833373,
        0.60963753, 0.07869276]])

In [121]:
np.random.randint(-10, 10, size=(4,4)) #exclusive

array([[ 2,  0,  6, -7],
       [-5, -9,  9, -6],
       [ 0, -4,  4,  5],
       [ 0,  6, -8, -7]], dtype=int32)

In [122]:
#identity matrix
np.identity(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [123]:
arr = np.array([[1,2,3]]) #make it 2 dim for repeating with axis 2d 
r = np.repeat(arr, 5,axis = 0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [124]:
ind = int(input("number idiot: "))
har = np.full((ind,ind) , 1)
for i in range(1,ind - 1):
    har[i, 1:ind-1] = 0
har[ind//2,ind//2] = 9

print(har)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
#### be careful when copying arrays 
a = np.array([1,2,3])
# b = a #directly pointing 
c = a.copy()
c[0]=24
a # a changes if direct

array([1, 2, 3])

Mathematics

In [ ]:
a = np.array([1,2,3,4])

# you can treat a as int and apply general operations 

a * 4 
a += 4

b = a.copy()
a + b + a

np.cos(a)
# for more scipy . . . . .

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

linear algebra

In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

#matrix mul

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [128]:
c = np.identity(5)
np.linalg.det(c)

# scipy linalg thing for more stuff

np.float64(1.0)

#statistics

In [130]:
stats = np.array([[1,2,3],[4,5,6]])
stats 


array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
np.min(stats,axis=1) #same max
np.sum(stats,axis = 1)

array([ 6, 15])

Reorganizing arrays

In [135]:
before = np.array([[1,2,3,19],[4,5,6,91]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[ 1  2  3 19]
 [ 4  5  6 91]]
[[[ 1  2]
  [ 3 19]]

 [[ 4  5]
  [ 6 91]]]


In [141]:
# vertical stacks 
v1 = np.array([1])
v2 = np.array([2])

np.vstack([v1,v2]) #hstack for horizontal

array([[1],
       [2]])

Load Data from file

In [148]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata.astype('int32')

array([[ 1,  2,  2,  3,  3,  4,  4,  5,  5, 56],
       [ 3,  5,  5,  6,  6,  5,  6,  7,  7,  7],
       [ 9,  8,  6,  5,  4,  3,  2,  4,  5,  6]], dtype=int32)

#### Boolean Masking and Advanced indexing


In [149]:
filedata > 5

array([[False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False, False, False,
         True]])

In [150]:
#you can index with a list in numpy
a = np.array([1,2,3,4])
a[[2,3]]

array([3, 4])

In [153]:
np.any(filedata>55 , axis = 0)

array([False, False, False, False, False, False, False, False, False,
        True])